### ISSUE TITLE
[FEAT] 메인 홈 / 챌린지 상세 레이아웃 구현

### ISSUE THREAD

**Issue by serim53** [E-CO-CO/Ecoco-Android#4]
## 🌎 이슈 요약
메인 홈 / 챌린지 상세 레이아웃 구현

<br/>

## ✅ To-Do

- [x] 메인 홈 화면 레이아웃 구현
- [x] 챌린지 상세 화면 레이아웃 구현
- [x] 챌린지 참여 다이얼로그 레이아웃 구현
